version: "3"
# Description of Containers:
#
#   authproxy   This is the oauth2_proxy container
#   upstream    This is the upstream app that is protected by the oauth2_proxy
#

services:
  # Google OAuth Proxy
  authproxy:
    build: .
    ports:
      - "80:4180"
    command: --cookie-secure=false --upstream="http://upstream:80" --http-address="0.0.0.0:4180" --provider oidc --oidc-issuer-url="https://outreach.oktapreview.com" --redirect-url="http://localhost/oauth2/callback" --email-domain="outreach.io"
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: super_secret_arbitrary_cookie_secret
      OAUTH2_PROXY_COOKIE_DOMAIN: localhost
      OAUTH2_PROXY_CLIENT_ID: <OIDC_CLIENT_ID>
      OAUTH2_PROXY_CLIENT_SECRET: <OIDC_CLIENT_SECRET>
    networks:
      - authproxy

  # NGINX example app
  upstream:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./example/index.html:/usr/share/nginx/html/index.html:ro"
      - "./example/nginx:/etc/nginx"
    networks:
      - authproxy

networks:
  authproxy:
    driver: bridge
